---
- name: "Create Application Group"
  become: yes
  group:
    name={{ app_group }}
    state=present
  when: ansible_system == 'Linux'
- name: "Create Application Account"
  become: yes
  user:
    name={{ app_username }}
    comment="Application Service Account for {{ app_name }}"
    group={{ app_group }}
    create_home=no
    home=/app/atlassian
    state=present
  when: ansible_system == 'Linux'
