---
- name: Extract Atlassian Application
  unarchive:
    src: "/app/src/atlassian-{{ app_name }}-{{ app_version }}.tar.gz"
    dest: "/app/atlassian/"
    owner: "{{ app_username }}"
    group: "{{ app_group }}"
- name: Create Symlink for Application
  file:
    src: "/app/atlassian/atlassian-{{ app_name }}-{{ app_version }}"
    dest: "{{ app_path }}"
    state: link
- name: Extract MySQL Connector J
  unarchive:
    src: "/app/src/mysql-connector-java-{{ mysql_connector_version }}.tar.gz"
    dest: "/app/src/"
    owner: "{{ app_username }}"
    group: "{{ app_group }}"
- name: Copy MySQL Library into Atlassian install
  copy:
    src: "/app/src/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar"
    dest: "{{ app_path }}/lib/"
    owner: "{{ app_username }}"
    group: "{{ app_group }}"
    mode: 0644
