---
- name: Install systemd config
  template:
    remote_src: no
    src: templates/systemd.service.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == "systemd"
- name: create systemd service directory
  file:
    path: "/etc/systemd/system/{{ app_name }}.service.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == "systemd"
- name: Install systemd override Config
  copy:
    remote_src: no
    src: files/systemd-override.conf
    dest: "/etc/systemd/system/{{ app_name }}.service.d/override.conf"
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == "systemd"
- name: Force systemd to reread configs
  systemd: daemon_reload=yes
- name: enable service and ensure it is not masked
  systemd:
    name: "{{ app_name }}"
    enabled: no
    masked: no
  when: ansible_service_mgr == "systemd"
